//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.VendingMachine.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ingenio.VendingMachine.Infrastructure.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product already choosed. Please complete purchase process.
        /// </summary>
        internal static string AlreadyChoosedProductMessage {
            get {
                return ResourceManager.GetString("AlreadyChoosedProductMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose your product before inserting money.
        /// </summary>
        internal static string ChooseProductBeforeMessage {
            get {
                return ResourceManager.GetString("ChooseProductBeforeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such product. Choose another one.
        /// </summary>
        internal static string NoProductInStockMessage {
            get {
                return ResourceManager.GetString("NoProductInStockMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products in purchase history.
        /// </summary>
        internal static string NoProductsExceptionMessage {
            get {
                return ResourceManager.GetString("NoProductsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such product in purchase history.
        /// </summary>
        internal static string NoSuchProductExceptionMessage {
            get {
                return ResourceManager.GetString("NoSuchProductExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product #{0} choosed. Amount inserted: {1}, amount remaining: {2}.
        /// </summary>
        internal static string PurchaseProcessMessage {
            get {
                return ResourceManager.GetString("PurchaseProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your product in the tray. Thanks.
        /// </summary>
        internal static string ThanksPurchaseMessage {
            get {
                return ResourceManager.GetString("ThanksPurchaseMessage", resourceCulture);
            }
        }
    }
}
